# Site settings
title: Alexey Grigorev - Data Scientist & ML Engineer
description: Personal page of Alexey Grigorev - Data Scientist & ML Engineer
author: Alexey Grigorev
email: alexey@datatalks.club
url: ""
baseurl: ""

# Build settings
markdown: kramdown
permalink: none

# Exclude from processing
exclude:
  - node_modules
  - vendor
  - old
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .bin/
  - .github/
  - .gitignore

# Default values
defaults:
  - scope:
      path: ""
    values:
      layout: default
